# yaml-language-server: $schema=https://raw.githubusercontent.com/Azure/azure-dev/main/schemas/v1.0/azure.yaml.json

name: chaos-demo
services:
  web:
    resourceName: chaos-cluster
    project: ./src/web
    dist: build
    language: python
    host: aks
    docker:
      image: web-app
      tag: latest
  api:
    resourceName: chaos-cluster
    project: ./src/api
    language: python
    host: aks
    docker:
      image: api-app
      tag: latest
    k8s:
      ingress:
        relativePath: api
