apiVersion: apps/v1
kind: Deployment
metadata:
  name: "api"
  labels:
    app: "api"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "api"
  template:
    metadata:
      labels:
        app: "api"
    spec:
      containers:
        - name: api
          image: criwjxfqayhhqse.azurecr.io/api-app:latest
          ports:
            - containerPort: 5000
          env:
            - name: APP_PORT
              value: "8080"
            - name: APP_VERSION
              value: "1.0.0"
            - name: AZURE_CLIENT_ID
              value: ${AZURE_AKS_IDENTITY_CLIENT_ID}
            - name: APPLICATIONINSIGHTS_CONNECTION_STRING
              value: InstrumentationKey=ec19d823-94a7-48a3-bd1b-23ae9dfb6ea4;IngestionEndpoint=https://westeurope-5.in.applicationinsights.azure.com/;LiveEndpoint=https://westeurope.livediagnostics.monitor.azure.com/;ApplicationId=a60da77e-8f52-47a3-9b94-b1d0b4140d55
            - name: OTEL_SERVICE_NAME
              value: "chaos-api"
            - name: OTEL_TRACES_SAMPLER_ARG
              value: "1"              
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "512m"
              memory: "512Mi"
            requests:
              cpu: "100m"
              memory: "128Mi"

---

apiVersion: v1
kind: Service
metadata:
  name: api

spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 5000
  selector:
    app: api