apiVersion: apps/v1
kind: Deployment
metadata:
  name: "api"
  labels:
    app: "api"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "api"
  template:
    metadata:
      labels:
        app: "api"
    spec:
      containers:
        - name: node
          image: criwjxfqayhhqse.azurecr.io/chaos-demo/api-chaos-demo:azd-deploy-1738157535
          ports:
            - containerPort: 5000
          env:
            - name: APP_PORT
              value: "8080"
            - name: APP_VERSION
              value: "1.0.0"
            - name: AZURE_CLIENT_ID
              value: ${AZURE_AKS_IDENTITY_CLIENT_ID}
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "512m"
              memory: "512Mi"
            requests:
              cpu: "100m"
              memory: "128Mi"


apiVersion: v1
kind: Service
metadata:
  name: api

spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 5000
  selector:
    app: api